name: Check or publish

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, ready_for_review]

jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    permissions:
      contents: read
    steps:
      # Deno fmt requires LF line endings on Windows.
      - run: git config --global core.autocrlf false

      - uses: actions/checkout@v6
      - uses: denoland/setup-deno@v2

      - run: deno task ci

  publish:
    needs: check
    if: ${{ github.ref_name == 'main' && github.event_name == 'push' }}
    runs-on: ubuntu-latest
    concurrency:
      group: jsr-publish-${{ github.repository }}
      cancel-in-progress: false
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: denoland/setup-deno@v2

      - name: Configure release tag author
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - run: deno task release
